apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }} 
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.name }} 
        image: {{ .Values.docker.image }}:{{ .Values.docker.tag }} 
         
        volumeMounts:
        - name: ncipher-config
          mountPath: {{ .Values.config.mount }} 
        - name: ncipher-socket
          mountPath: {{ .Values.socket.mount }}
      volumes:
      - name: ncipher-config
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }} 
      - name: ncipher-socket
        hostPath:
          path: {{ .Values.socket.hostPath }}
