---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }} 
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }} 
  selector:
    matchLabels:
      name: {{ .Values.pv.name }} 
   
