---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.hsm.pvc.name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.hsm.pvc.size }} 
  selector:
    matchLabels:
      name: {{ .Values.hsm.pv.name }}
   
