apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hsm.pv.name }}
  labels:
    name: {{ .Values.hsm.pv.name }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.hsm.pv.size }}
  accessModes:
    - ReadOnlyMany
  nfs:
    server:  {{ .Values.nfs.server }}
    path: {{ .Values.hsm.config.nfsPath }}
